baseURL = '//manavjain.sh/'
languageCode = 'en-us'
title = "Manav Jain"
theme = 'nightfall'

[menu]
  [[menu.header]]
    name = "blog"
    weight = 1
    url = "posts"
  [[menu.header]]
    name = "wiki"
    weight = 2
    url = "notes"
  #[[menu.header]]
    #name = "technical_writing"
    #weight = 3
    #url = "technical_writing"
    

[params]
user = "reader"
hostname = "manavjain.sh"
favicon = "favicon.ico"
  [params.author]
    name = "Manav Jain"  # Website and RSS feed author
 

#[[params.social]]
#key = 0
#name = "the other me"
#url = "https://manavjain.com"


